# @package _global_
#
# Vibrational-modes experiment on the torus, should be the Fourier basis
#
# Usage:
#   python reg_cob.py +vibration_experiment=trivial_vibration
defaults:
  - _self_

material:
  _target_: infidictionary.material.ConstantMaterial
  diffusivity: 1.0
  domain_sampler:
    _target_: infidictionary.domain_samplers.SquareSampler

# Isometry-check domain sampler must match the airplane domain
callbacks:
  isometry_check:
    _target_: infidictionary.callbacks.IsometryCheck
    dictionary: ${initial_dictionary}
    domain_sampler:
      _target_: infidictionary.domain_samplers.SquareSampler
    frequency: 100
    density: 100
    indices:
      - [ 0,  0, 0]
      - [-1,  0, 0]
      - [ 0, -1, 0]
      - [ 1,  0, 0]
      - [ 0,  1, 0]

wandb:
  project: BasisLearning-trivial
  tags:
    material: torus
    method: heat_qform
