# @package _global_
#
# Usage:
#   python concept_basis.py +concept_experiment=sds_fourier
#   python concept_basis.py +concept_experiment=sds_fourier wandb=enabled

defaults:
  - override /neural_fields@neural_isometry.scalar_field_partial: old
  - _self_

caption: "Joseph Fourier's Face"

concept_loss:
  _target_: infidictionary.concept.SDSLoss
  model_id: "runwayml/stable-diffusion-v1-5"
  guidance_scale: 50.0
  t_range: [0.02, 0.98]
  render_size: 512
  n_augmentation_trials: 0
  t_batch_size: 1
  weighted_loss: false

mean_function: null

K: 1
coefficient_decay: 0.5
batch_size: 2
grad_accumulation_steps: 16

# callbacks:
#   isometry_check:
#     _target_: infidictionary.callbacks.IsometryCheck
#     dictionary: ${initial_dictionary}
#     domain_sampler:
#       _target_: infidictionary.domain_samplers.SquareSampler
#       stratified: True
#       add_noise: False
#       height: 1.
#       width: 1.
#     frequency: 100
#     density: 100
#     indices:
#       - [ 0,  0, 0]
#       - [ 1,  0, 0]
#       - [ 0,  0, 1]
#       - [-1,  0, 1]
#       - [ 0,  0, 2]

wandb:
  project: BasisLearning-ConceptBasis
  tags:
    concept: Fourier
    method: SDS
