
_target_: infidictionary.networks.FourierDistortedFieldV4

n_modes: 256
freq_strides: 3
spatial_hidden_dims:
  - 256
  - 256
  - 256
n_time_freqs: 256
low_freq: 0.0
high_freq: 10.0
low_t: 0.0
high_t: 1.0
gamma: 1.0

activation:
  _target_: torch.nn.SiLU
  _partial_: true
