_target_: infidictionary.utils.HybridNeuralField
input_dim: 2
output_dim: 1
n_features: 64
sigma: 10.0
ff_hidden_dims:
  - 256
  - 256
mlp_hidden_dims:
  - 256
  - 256
activation:
  _target_: torch.nn.ReLU
  _partial_: true
