_target_: infidictionary.datasets.BasisRandomGenerator
dictionary: 
  _target_: infidictionary.dictionaries.FourierDictionary
  domain_dim: 2
  num_channels: 1
  index_geom_p: 0.3
atom_indices:
  - [0, 0]
  - [1, 0]
  - [0, 1]
  - [-1, 0]
  - [0, -1]
diffeomorphism:
  _target_: infidictionary.diffeomorphisms.ShirlyChiu
