_target_: infidictionary.datasets.BasisRandomGenerator
domain_sampler:
  _target_: infidictionary.domain_samplers.SquareSampler
  stratified: true
  add_noise: true
  height: 1.0
  width: 1.0
domain_sample_size: 32
n_functions: 1000
dictionary:
  _target_: infidictionary.dictionaries.FourierDictionary
  domain_dim: 2
  num_channels: 1
  index_geom_p: 0.3
atom_indices:
  - [0, 0]
  - [1, 0]
  - [0, 1]
  - [-1, 0]
  - [0, -1]
diffeomorphism: null
