# @package _global_
#
# Minimises E_a = ∫ D(x) ‖∇(Qφ_a)(x)‖_2 dx, finds the 1-Laplacians
#
# Usage:
#   python reg_cob.py +tv_experiment=1d_tv
defaults:
  - override /neural_fields@neural_isometry.scalar_field_partial: experimental2 
  - _self_


initial_dictionary:
  num_channels: 1
  domain_dim: 1
  p: 0.1

neural_isometry:
  coords_dim: 1
  channels_dim: 1

model_state_kwargs:
  num_steps: 200

isometry_optimizer_callable:
  lr: 0.0005

tail_probability: 0.042
num_tail_samples: 0
grad_accumulation_steps: 16


regularizer:

  _target_: infidictionary.regularizers.TVMaterialRegularizer
  domain_sampler: 
    _target_: infidictionary.domain_samplers.LineSegmentSampler
    stratified: true
    add_noise: true
  domain_sample_size: 100
  material:
    _target_: infidictionary.material.FourierTorusMaterial
    frequencies: [0]
    phases: [0.0]
    amplitude: 0.0
    base_diffusivity: 1.0
  mass_threshold: 0.01
  sigma: 0.01


checkpointing:
  checkpoint_every_n_steps: 10

wandb:
  project: BasisLearning-tv
  tags:
    material: rod
    method: tv-dirichlet
