defaults:
  - function_generator: fourier_2d # the forward problem
  - neural_isometry: half_density_kumaraswamy_radial
  - dictionaries@initial_atoms: fourier_2d
  - hydra: default
  - wandb: disabled # set to enabled for wandb logging
  - _self_
  - override hydra/hydra_logging: none # hack to fix the logging code
  - override hydra/job_logging: none # hack to fix the logging code


optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  _partial_: true

scheduler: null

# training hyperparameters
n_epochs: 500000
domain_sample_size: 100
n_functions: 1000
batch_size: 100
atom_index_batch_size: 100
grad_accumulation_steps: 10
energy_smoothing_alpha: 0.99
n_reduced_order: null

atom_index_distribution:
  _target_: torch.distributions.Geometric
  probs: 0.2
