_target_: basis_learning.bases.MixtureBasis
bases:
  fourier:
    _target_: basis_learning.bases.FourierBasis
    num_basis_elements: 9
  tent_basis:
    _target_: basis_learning.bases.TentBasis
    total_rows: 3
    total_cols: 3
