"""Shared visualization and utility helpers for learning-projections notebooks."""

import math
import torch
import numpy as np
import matplotlib.pyplot as plt


# ── Display helpers ──────────────────────────────────────────────────────────

def field_to_img(f_N1, N: int) -> np.ndarray:
    """(N²,1) or (N²,) tensor → (N, N) float array for imshow(origin='lower').

    ij-indexing: first dim = x (columns), second = y (rows), so we transpose.
    """
    return f_N1.detach().cpu().float().squeeze(-1).reshape(N, N).T.numpy()


def to_rgb_image(field_N3, N: int) -> np.ndarray:
    """(N², 3) tensor → (N, N, 3) float array, globally normalised to [0, 1]."""
    img = field_N3.detach().cpu().float().reshape(N, N, 3)
    lo = img.amin(dim=(0, 1), keepdim=True)
    hi = img.amax(dim=(0, 1), keepdim=True)
    return ((img - lo) / (hi - lo + 1e-8)).numpy()


def render(v_img: np.ndarray):
    """Normalise a (H, W, C) field snapshot for imshow.

    C == 1 → diverging RdBu_r colourmap centred at zero.
    C >  1 → each channel normalised to [0, 1] for RGB display.

    Returns (image, cmap, vmin, vmax) — unpack directly into ax.imshow().
    """
    C = v_img.shape[-1]
    if C == 1:
        vmax = float(np.abs(v_img[:, :, 0]).max()) + 1e-8
        return v_img[:, :, 0], "RdBu_r", -vmax, vmax
    lo  = v_img.min(axis=(0, 1), keepdims=True)
    hi  = v_img.max(axis=(0, 1), keepdims=True)
    rng = hi - lo
    display = np.divide(v_img - lo, rng, out=np.full_like(v_img, 0.5), where=rng > 1e-6)
    return np.clip(display, 0, 1), None, None, None


# ── Physics helpers ──────────────────────────────────────────────────────────

def periodic_gaussian_mixture(coords, specs, weights=None):
    """Mixture of anisotropic, periodic (torus-aware) Gaussians.

    coords  : (N, 2) coordinates in [0, 1]²
    specs   : list of dicts with keys:
                'center' (x, y), 'angle' (radians), 'sigmas' (sigma_x, sigma_y)
    weights : list of floats (default: uniform 1.0)

    Returns (N, 1) field values (not normalised, max ≈ 1 per component).
    """
    if weights is None:
        weights = [1.0] * len(specs)
    result = torch.zeros(coords.shape[0], 1, device=coords.device, dtype=coords.dtype)
    for spec, w in zip(specs, weights):
        mu = torch.tensor(spec['center'], device=coords.device, dtype=coords.dtype)
        theta = spec['angle']
        sx, sy = spec['sigmas']
        c, s = math.cos(theta), math.sin(theta)
        R_mat = torch.tensor([[c, -s], [s, c]], device=coords.device, dtype=coords.dtype)
        prec  = R_mat @ torch.diag(
            torch.tensor([1.0 / sx**2, 1.0 / sy**2], device=coords.device, dtype=coords.dtype)
        ) @ R_mat.T
        delta = coords - mu
        delta = delta - torch.round(delta)  # shortest path on torus
        maha  = (delta @ prec * delta).sum(dim=-1, keepdim=True)
        result = result + w * torch.exp(-0.5 * maha)
    return result


# ── EulerianIsometry visualisation ──────────────────────────────────────────

def visualize_generator_U(isometry, coords_vis, N_vis: int, timesteps, device):
    """(R+1) × len(timesteps) figure: U columns and exp(K_R − K_Rᵀ).

    Rows 0..R-1 : spatial plot of u_r(t, ·) at each timestep.
                  C=1  → grayscale RdBu_r imshow + colorbar.
                  C>1  → RGB imshow (channels globally normalised to [0, 1]).
    Row R       : R×R heatmap of exp(K_R − K_Rᵀ) — the finite rotation
                  generated by K_R at each timestep.

    Parameters
    ----------
    isometry   : EulerianIsometry (.rank, .channels_dim, .time_embedding,
                 .function_field, ._compute_kr)
    coords_vis : (N_vis², d) tensor on `device`, from a no-noise stratified grid
    N_vis      : grid size per dimension
    timesteps  : 1-D tensor of time values to visualise
    device     : torch device
    """
    R   = isometry.rank
    C   = isometry.channels_dim
    N   = coords_vis.shape[0]
    n_t = len(timesteps)

    fig, axes = plt.subplots(
        nrows=R + 1, ncols=n_t,
        figsize=(4 * n_t, 4 * (R + 1)),
        gridspec_kw={"hspace": 0.05, "wspace": 0.05},
    )
    if n_t == 1:
        axes = axes[:, None]

    with torch.no_grad():
        for j, t_val in enumerate(timesteps):
            t_sc    = float(t_val)
            t_batch = torch.full((N,), t_sc, device=device, dtype=coords_vis.dtype)
            t_emb   = isometry.time_embedding(t_batch)            # (N, emb_dim)
            U       = isometry.function_field(t_emb, coords_vis)  # (N, R, C)

            t_emb_1 = isometry.time_embedding(t_batch[:1])        # (1, emb_dim)
            K_R     = isometry._compute_kr(t_emb_1)[0]            # (R, R)
            O       = torch.matrix_exp(K_R - K_R.T)               # (R, R) orthogonal

            for r in range(R):
                ax  = axes[r, j]
                u_r = U[:, r, :]  # (N, C)
                if C == 1:
                    im = ax.imshow(
                        field_to_img(u_r, N_vis),
                        origin='lower', extent=[0, 1, 0, 1], cmap='RdBu_r',
                    )
                    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
                else:
                    ax.imshow(to_rgb_image(u_r, N_vis), origin='lower', extent=[0, 1, 0, 1])
                ax.set_title(f'$u_{{{r}}}$,  t={t_sc:.2f}', fontsize=8)
                ax.set_xlabel('x'); ax.set_ylabel('y')
                ax.set_aspect('equal')

            ax = axes[R, j]
            im = ax.imshow(O.cpu().float().numpy(), cmap='RdBu_r', vmin=-1, vmax=1)
            plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
            ax.set_title(f'$\\exp(K_R\\!-\\!K_R^\\top)$,  t={t_sc:.2f}', fontsize=8)
            ax.set_xlabel('col'); ax.set_ylabel('row')

    plt.suptitle(
        'Rows $0..R\\!-\\!1$: columns of $U(t,\\cdot)$;  '
        'Row $R$: finite rotation $\\exp(K_R - K_R^\\top)$',
        fontsize=11,
    )
    plt.tight_layout()
    plt.show()
