# @package _global_
#
# Usage:
#   python reg_cob.py +euclidean_group=translation

defaults:
  - override /neural_fields@neural_isometry.scalar_field_partial: nerf_spatiotemporal_field
  - _self_

initial_dictionary:
  num_channels: 1
  steepness: 2.0
  tiebreak_eps: 1.0e-3

neural_isometry:
  base_acceleration: 1
  channels_dim: 1


model_state_kwargs:
  num_steps: 100

tail_probability: 0.0001 # 0.011
num_tail_samples: 32 # 0
grad_accumulation_steps: 8
max_grad_norm: 1.0

regularizer:
  _target_: infidictionary.regularizers.EuclideanGroup
  domain_sample_size: 64
  translation: [0.2, 0.1]
  rotation_quarter_turns: [0, 0]
  mirrors: [False, False]

checkpointing:
  checkpoint_dir: outputs/checkpoints
  checkpoint_every_n_steps: 2

wandb:
  project: BasisLearning-euclidean-group
  tags:
    method: euclidean_group
