_target_: infidictionary.index_sampler.HybridSampler
index_samplers:
  geometric:
    _target_: infidictionary.index_sampler.GeometricIndexSampler
    base_p: 0.05
    final_p: 0.05
    gamma: 1.
  uniform:
    _target_: infidictionary.index_sampler.UniformIndexSampler
    n_indices: 20
weights:
  geometric: 0.5
  uniform: 0.5
