_target_: infidictionary.neural_isometries.EulerianIsometry
coords_dim: 2
channels_dim: 1
scalar_field_partial:
  _target_: infidictionary.utils.TimeEvolvingField
  _partial_: true
  base_field_partial:
    _target_: infidictionary.utils.MLPNeuralField
    _partial_: true
    hidden_dims:
      a: 16
      b: 32
      c: 64
      d: 32
    activation:
      _target_: torch.nn.ReLU
      _partial_: true
