defaults:
  - /neural_fields@scalar_field_partial: old # TODO: gotta fix it
  - _self_

_target_: infidictionary.neural_isometries.EulerianIsometry
coords_dim: 2
channels_dim: 1
rank: 2
base_acceleration: 10.
atom_shuffling_K: 5

gradient_checkpointing: true

scalar_field_partial:
  _partial_: true


