defaults:
  - /diffeomorphisms@diffeomorphism: kumaraswamy_radial
  - _self_

_target_: infidictionary.neural_isometries.HalfDensityIsometry
initial_diffeomorphism: 
  _target_: infidictionary.diffeomorphisms.IdentityFlow
