_target_: infidictionary.neural_isometries.GeneralizedIsometry
first_change_of_domain:
  _target_: infidictionary.neural_isometries.lagrangian.LagrangianIsometry
  diffeomorphism:
    _target_: infidictionary.diffeomorphisms.ShirlyChiu

ode_isometry:
  _target_: infidictionary.neural_isometries.lagrangian.LagrangianIsometry
  diffeomorphism:
    _target_: infidictionary.diffeomorphisms.continuous_time.CTRadialFlow
    dimensions: 2
    gamma: 1
    use_adjoint: True
    method: dopri5
    rtol: 0.000001
    atol: 0.000001
    
last_change_of_domain: null
