_target_: infidictionary.dictionaries.FourierDictionary
domain_dim: 2
num_channels: 1
distribution_type: geometric
distribution_kwargs:
  p: 0.3
# distribution_type: zeta
# distribution_kwargs:
#   a: 1.1
