_target_: infidictionary.dictionaries.MixedDictionary
atoms:
  fourier:
    _target_: infidictionary.dictionaries.RadialFourierDictionary
    num_atoms: 9
  tent_basis:
    _target_: infidictionary.dictionaries.RadialTentDictionary
    total_rows: 3
    total_cols: 3
